-- The roster becomes term-scoped, and `members.active` goes away (§7, §4.7).
--
-- Two changes that only make sense together, which is why they share a file.
--
-- 1. `member_directory` was ONE ROW PER MEMBER, hard-scoped to current_term().
--    It is now ONE ROW PER (MEMBER, TERM), and the officer picks the term. The
--    numbers on a row — points, events attended, the rate, dues — are all
--    computed for THAT ROW'S term, so choosing Spring 2026 shows Spring 2026's
--    figures rather than this term's figures under last term's heading. That
--    was the whole risk in adding a term control: an all-time denominator
--    against a current-term numerator understates every rate and still looks
--    plausible (migration 14 says so about events_possible), and a term filter
--    layered over current-term aggregates fails the same way.
--
-- 2. `members.active` is DROPPED. A hand-ticked boolean was the only answer to
--    "is this person still in the club", and nothing kept it true: it defaulted
--    to true, the roster import could set it, and after that it drifted. Term
--    membership answers the same question from evidence — see the `roster` CTE
--    below — so the flag is not being replaced by a better flag, it is being
--    replaced by a derivation.
--
-- ⚠️ DROP AND CREATE, not `create or replace`, and the reason is a rule this
-- repo has broken before: replace can only APPEND columns, and this removes
-- one (`active`) and renames another (`dues_paid_current_term` →
-- `dues_paid_term`). A drop is permitted for exactly that, on the condition
-- that the same migration re-issues the grants — which here means re-issuing
-- the REVOKES, because migrations 15 and 22 left this view with no grant to any
-- API role at all. See section 2; it is the part that is easy to leave out and
-- impossible to see afterwards.
--
-- 🪤 The rename is legal exactly once, in this migration, because this is the
-- only reason the view is being dropped. `dues_paid_current_term` would have
-- become an outright lie on a row scoped to some other term.

-- ---------------------------------------------------------------------------
-- 1. member_directory, one row per (member, term).
-- ---------------------------------------------------------------------------

drop view public.member_directory;

create view public.member_directory as
-- Every term the database knows about. A superset of the terms `roster` can
-- produce, which is all it has to be — `possible` is left-joined FROM roster,
-- so a term in here that nobody belongs to costs one unused row.
--
-- 🪤 Never a typed literal (§4.7). Event terms are generated by term_of(), the
-- adjustment default is current_term(), and the joining term is term_of() over
-- joined_at. current_term() is unioned in so the current term exists here even
-- in an empty database.
with all_terms as (
  select public.current_term() as term
  union
  select e.term from public.events e where e.term is not null
  union
  select pa.term from public.point_adjustments pa
  union
  select ct from public.dues_payments dp, unnest(dp.covered_terms) as ct
    where dp.voided_at is null
  union
  select public.term_of(m.joined_at) from public.members m
),
-- The attendance-rate denominator, per term. Migration 14 hoisted this out of
-- the select list so events_possible and attendance_rate could not disagree;
-- it stays hoisted for the same reason and gains a term key.
possible as (
  select t.term,
         (select count(*)
            from public.events e
           where e.term = t.term
             and e.status = 'published'
             and e.ends_at < now()) as events_possible
    from all_terms t
),
attendance_agg as (
  select a.member_id,
         e.term,
         count(*)                   as events_attended,
         coalesce(sum(e.points), 0) as attendance_points
    from public.attendance a
    join public.events e on e.id = a.event_id
   where a.status = 'present'
     and e.status <> 'cancelled'
   group by a.member_id, e.term
),
bonus_agg as (
  select member_id,
         term,
         coalesce(sum(points), 0) as bonus_points
    from public.point_adjustments
   where voided_at is null
   group by member_id, term
),
dues_agg as (
  select distinct dp.member_id, ct as term
    from public.dues_payments dp, unnest(dp.covered_terms) as ct
   where dp.voided_at is null
),
-- 📌 THE MEMBERSHIP RULE, and the thing to read before trusting this screen.
--
-- A member is on the roster for a term if there is EVIDENCE they were part of
-- the club in it: they were marked present at one of its events, they were
-- granted or docked points in it, their dues cover it, or they joined during
-- it. `joined_at` is not null, so every member always appears in at least one
-- term and nobody can fall out of the roster entirely.
--
-- ⚠️ The consequence, stated because it will look like a bug in week one: at
-- the start of a semester, before any event has happened, the current term's
-- roster is only the members who joined during it or have already paid dues
-- covering it. That is the rule working, not failing — but the empty state on
-- the directory has to say so, and it does.
--
-- A UNION, not UNION ALL: the four sources overlap heavily and the join below
-- would multiply rows.
roster as (
  select member_id, term from attendance_agg
  union
  select member_id, term from bonus_agg
  union
  select member_id, term from dues_agg
  union
  select m.id, public.term_of(m.joined_at) from public.members m
)
select
  m.id,
  m.eid,
  m.full_name,
  m.email,
  m.source,
  m.joined_at,
  -- The scope key. Every aggregate to the right of it is computed for this
  -- term and no other.
  r.term,
  coalesce(aa.events_attended, 0)   as events_attended,
  coalesce(aa.attendance_points, 0) as attendance_points,
  coalesce(ba.bonus_points, 0)      as bonus_points,
  coalesce(aa.attendance_points, 0)
    + coalesce(ba.bonus_points, 0)  as total_points,
  -- ⚠️ These two stay ALL-TIME, and they are now the only columns on the view
  -- that are not scoped to the row's term. A pending row from last term still
  -- needs an officer, and "when did we last see this person" is an all-time
  -- question — the same call migration 14 made, and it matters more here
  -- because everything around them moved. The UI must label both.
  (select count(*) from public.attendance a
    where a.member_id = m.id and a.status = 'pending')      as pending_count,
  (select max(a.submitted_at) from public.attendance a
    where a.member_id = m.id and a.status = 'present')      as last_seen_at,
  p.events_possible,
  round(
    coalesce(aa.events_attended, 0)::numeric
      / nullif(p.events_possible, 0),
    4
  )                                                         as attendance_rate,
  m.notes,
  m.custom_fields,
  m.updated_at,
  -- Renamed from dues_paid_current_term. Same derivation — a live payment whose
  -- covered_terms contains the term — but the term is now the row's, not the
  -- clock's. Still calculated, still never ticked.
  (exists (
     select 1 from public.dues_payments dp
      where dp.member_id = m.id
        and dp.voided_at is null
        and dp.covered_terms @> array[r.term]
   ))                                                       as dues_paid_term
from roster r
join public.members m on m.id = r.member_id
left join attendance_agg aa on aa.member_id = r.member_id and aa.term = r.term
left join bonus_agg      ba on ba.member_id = r.member_id and ba.term = r.term
left join possible       p  on p.term = r.term;

-- ---------------------------------------------------------------------------
-- 2. Re-issue the revokes. NOT OPTIONAL.
-- ---------------------------------------------------------------------------
--
-- 🔓 A dropped-and-recreated view re-inherits migration 12's default
-- privileges, which is how anon got read access to this view in production
-- once already (migration 15 documents the finding). A view has no RLS, so a
-- grant here is the whole of the protection. member_directory carries eid and
-- email and must be reachable only through the service-role client behind
-- requireOfficer(), exactly as migration 22 left it.
--
-- tests/security.test.ts asserts this; it allows `leaderboard` and nothing
-- else.
revoke all on public.member_directory from anon;
revoke all on public.member_directory from authenticated;

-- ---------------------------------------------------------------------------
-- 3. leaderboard loses `where m.active` and gains the roster rule.
-- ---------------------------------------------------------------------------
--
-- The public board excluded inactive members. With the flag gone it would have
-- ranked every member ever recorded, alumni included, most of them on zero —
-- so the trim has to come from somewhere, and the honest source is the same
-- membership rule the directory now uses. Defining the board OVER
-- member_directory rather than restating that rule is deliberate: two copies
-- would eventually disagree about who is in the club, and this repo has the
-- scar (§4.4, "two sources for one fact").
--
-- 📌 `create or replace`, so migration 8's `grant select to anon, authenticated`
-- SURVIVES and is deliberately not restated. The four output columns keep their
-- names, types and order; only the FROM and the WHERE change.
--
-- 🔓 Selecting FROM member_directory does not widen what anon can read. This
-- view is owner-rights too, so the inner view's (absent) grants are not
-- consulted, and the projection is still id / full_name / total_points / term —
-- no eid, no email. §6's rule that the board omits both is unchanged, and the
-- reason it is safe is the projection, not the inner view's permissions. Never
-- add a column here without re-reading that.
create or replace view public.leaderboard as
select
  md.id,
  md.full_name,
  md.total_points,
  md.term
from public.member_directory md
where md.term = public.current_term()
order by md.total_points desc, md.full_name;

-- ---------------------------------------------------------------------------
-- 4. Drop members.active.
-- ---------------------------------------------------------------------------
--
-- Both views above no longer reference it, which is why this is the last step
-- rather than the first. The partial index goes with it.
--
-- 🔴 IRREVERSIBLE. Any member an officer had marked inactive becomes
-- indistinguishable from one they had not; there is no column to put the mark
-- back into. Accepted on 2026-08-25 — production holds zero members, so there
-- were no marks to lose.
drop index if exists public.members_active_idx;

alter table public.members
  drop column active;

-- ---------------------------------------------------------------------------
-- 5. Reserve the two new directory column names.
-- ---------------------------------------------------------------------------
--
-- A custom field keyed `term` or `dues_paid_term` would shadow a real column in
-- the sort and filter namespace, which is the collision this constraint exists
-- to prevent. `active` and `dues_paid_current_term` STAY reserved even though
-- neither is a column any more: freeing a key lets a definition claim a name
-- that older audit rows, exports and saved presets still refer to.
alter table public.member_field_definitions
  drop constraint member_field_definitions_key_not_builtin;

alter table public.member_field_definitions
  add constraint member_field_definitions_key_not_builtin
    check (key not in (
      'id','eid','email','name','full_name','active','source','joined_at',
      'notes','custom_fields','total_points','attendance_points','bonus_points',
      'events_attended','events_possible','attendance_rate','pending_count',
      'last_seen_at','term',
      -- Stage 6.5: dues left the custom-field mechanism entirely.
      'dues','dues_paid','dues_paid_current_term','dues_paid_term'
    ));

-- ---------------------------------------------------------------------------
-- 6. The terms the roster control offers.
-- ---------------------------------------------------------------------------
--
-- 🪤 A function rather than `select term from member_directory` deduped in
-- JavaScript, and the reason is the trap READ_CHUNK exists for: the view is now
-- one row per member per term, so that read is members × terms — 4,000 rows at
-- §2.2's worst case — and the hosted project's PostgREST `max_rows` would
-- silently return a short list. A truncated term list does not look broken; it
-- looks like the club had no Spring 2026, and the officer has no way to tell.
--
-- Ordered newest first by term_index(), never lexicographically: 'Fall 2026' <
-- 'Spring 2026' is true as a string and false as a calendar fact, and this repo
-- has that scar (§4.7). current_term() is unioned in so the control always
-- offers the term it defaults to, even in an empty database where nobody has
-- joined yet.
create or replace function public.member_terms()
returns table (term text)
language sql
stable
security definer
set search_path = ''
as $$
  select t
  from (
    select d.term as t from public.member_directory d
    union
    select public.current_term()
  ) x
  where t is not null
  order by public.term_index(t) desc
$$;

-- 🔓 Officer-only, like the view it reads. The term list is not sensitive in
-- itself, but this function is `security definer` over a view that carries eid
-- and email, and a definer function reachable by anon is the shape of mistake
-- migration 21 was written to fix. Nothing but the service-role client calls it.
revoke execute on function public.member_terms() from anon;
revoke execute on function public.member_terms() from authenticated;
